### PR TITLE
Refactoring, build updates

### PR DESCRIPTION
**Pull request by tillig**
This doesn't solve all the problems, but it may uncover some ways to test. In particular, I updated the class fixture for the hosted app tests so the test hosted server is a singleton for the class - not recreated from scratch on every unit test request - and I find the unit tests no longer pass. I'm not sure if it's a threading thing or what yet, but I think it uncovers some new verification avenues. My gut says the tests should pass if the _host_ is a singleton (like a real web app) but the _client instance_ is per test.

It looks like a lot, though, because it includes:

- Update the `.editorconfig` and analyzer rulesets to align with core Autofac.
- Update the `.csproj` settings to be ordered and set up like core Autofac. (Allows us to "diff" between the projects to see what's changed/different or update easier.)
- Enable `ImplicitUsings` where possible and remove unnecessary usings.
- Switch to file-scoped namespaces.
- Resolve all new analyzer warnings/issues.
- Update the packaging to use .snupkg as the format for symbols, updated the README to be formatted for inclusion in the package.
- Removed the feature factory class - we don't need it anymore since it's just a `new` call.

I'm not sure how better to collaborate in a forked branch that will result in an overall PR to a different repo. 😆  So... PR to a PR?

I can pull from upstream to get any changes you end up making and can then submit further PRs to collaborate.

I think the next step here is to figure out why the integration tests no longer pass when using a singleton host, though. That seems kind of red-flag-ish. It may be that I incorrectly set up the class fixture, but I'm pretty confident it looks right.

### CODE REVIEW

**Review by alsami — APPROVED** [review]

**Comment by alsami** [comment]
Thanks for this. I will check the failing tests and see if I can fix it.

**Comment by alsami** [comment]
> I think the next step here is to figure out why the integration tests no longer pass when using a singleton host, though. That seems kind of red-flag-ish. It may be that I incorrectly set up the class fixture, but I'm pretty confident it looks right.

So I think it's not only a test problem, the multitenancy completely stopped working again for some reason, also for the sandbox projects. 

I can't seem to find any code change that would relate to this failure to be honest. I am still investigating.

**Comment by alsami** [comment]
Okay I made a bit of progress:

Apparently directly composing `RequestServiceFeature` behaves different. The sandbox projects are broken, unless I add back the factory that has been removed with your PR - then it works again which makes absolutely no sense.

This does still not fix the tests, given that the `TestHost` apparently acts differently when it is initialized once and used for the entire test run of a specific class. My guess is that this won't be a problem for real life scenario, it's more like an implementation detail of the `TestServer` itself. 

Will investigate further later, need to get back to work.

**Comment by tillig** [comment]
> unless I add back the factory that has been removed with your PR - then it works again which makes absolutely no sense

What? That... Is so weird. If I get more time I'll see if I can figure it out.

**Pull request merged**
